version: "3.8"

services:

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=$POSTGRES_DATABASE
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - my_network

  app:
    depends_on:
      - postgres
    build: ./backend/chuchu
    restart: on-failure
    env_file: ./.env
    ports:
      - "$SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT"
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url"  : "jdbc:postgresql://postgres:5432/$POSTGRES_DATABASE?sslmode=disable",
          "spring.datasource.username" : "$POSTGRES_USER",
          "spring.datasource.password" : "$POSTGRES_PASSWORD",
          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
          "spring.jpa.hibernate.ddl-auto" : "update"
        }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    networks:
      - my_network
    
  ionic:
    build: ./frontend/portal
    ports:
      - "8100:8100"
    networks:
      - my_network
  
  admin_ionic:
    build: ./frontend/portal
    ports:
      - "8101:8101"
    networks:
      - my_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
      - ionic
    networks:
      - my_network
  
networks:
  my_network:
    driver: bridge

volumes:
  pg-data: