version: "3.8"

services:
  neo4j:
    build:
      context: ./neo4j
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=none
    volumes:
      - neo-data:/var/lib/neo4j/data
    networks:
      - my_network

  postgres:
    build:
      context: ./postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=$POSTGRES_DATABASE
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  pg-data:
  neo-data:
